### PR TITLE
smol changes

### PR DESCRIPTION
**Pull request by andrijajocic**
very smol changes that appeal to my inner ocd pls accept :)

### CODE REVIEW

**Comment by andrijajocic** [comment]
accidentally closed sorry

**Review by Almantask — COMMENTED** [review]
All good.

**Review by Almantask — APPROVED** [review]

**Review by Alumniminium — APPROVED** [review]
Hahahahah wow, breaking changes xD

**Comment by Developeneur** [comment]
@andrijajocic Is this pull request still needed?

**Comment by andrijajocic** [comment]
It should be merged, no idea why it isn't. Thanks for reminding me.

**Pull request merged**
