### PR TITLE
.NET Core CI

### PR DESCRIPTION
**Pull request by andrijajocic**

### CODE REVIEW

**Comment by norarrsgd** [comment]
@andrijajocic you were using an incorrect version number in the yml file. i pushed a change from **3** to **3.1.100**

**Review by Almantask — APPROVED** [review]
Looks good. It was done like that, because there was no 3.1 at the time.

**Comment by andrijajocic** [comment]
Thank you, @kuromukira. I didn't know there was already a 3.1 version of .NET Core.

**Comment by andrijajocic** [comment]
@lethern please review the pull request, this has been on hold for an arbitrarily long amount of time

or @Almantask can manually merge it, both methods suffice.

**Review by lethern — APPROVED** [review]

**Pull request merged**
